---
title: "DSCI 532 Project Proposal"
output: github_document
---


## Overview

Recent decades have seen violent crime in the U.S. decrease nationwide, but not all jurisdictions have experienced this decrease. In fact, there is considerable heterogeneity in violent crime rates among American cities, and violent crime continues to be major problem for many of them. For this reason, it is useful to look at more granular data about violent crime. To do so, we propose building a visualization app that will allow users to compare the violent crime rates and patterns in violent crime between multiple cities. Our app will allow users to specify a time period, a set of cities, and a type of crime to compare. Users will be able to see the long term trends in crime rates for the cities they specify, as well as look at the composition of violent crime for a specific year across those cities.  


## Data Description

Our dataset comes from the Marhsall Project, which compiled crime data  for major American cities from the FBI's Uniform Crime Reporting (UCR) Program. The dataset covers the period from 1975 - 2015, and contains information on sixty-eight cities, as well as national averages. For this project, we will be looking only at crime rates that are normalized by population (i.e. crime per 100,000 people). For each city, we have five annual crime rates: total violent crime rate and crime rates for four specific types of violent crime (assault, homicide, rape, and robbery).


#### Key Variables
|Variable Name |Description |Type |
|---------|------------|-----|
|`department_name`| | |
|`year`| | |
|`violent_per_100k`| | |
|`homs_per_100k`| | |
|`rape_per_100k`| | |
|`rob_per_100k` | | |
|`agg_ass_per_100k`| | |

## Usage Scenario and Tasks

A crime analyst reads an article claiming that violent crime in the Midwest have been falling in the past 25 years. To get a richer understanding of crime in the Midwest, she decides to use our app to compare the total violent crime rates accross a set of large Midwestern cities: Cincinnati, OH;  Chicago, IL; St. Louis, MO;  Milwaukee, WI; and Minneapolis, MN. To do this she selects the cities, a range of years, and a type of violent crime in the side bar panel of our app. Looking at a time series plot, she notices that there were large decreases in violent crime in Chicago throughout the 1990s, while crime rates in other Midwestern cities stayed fairly constant over the same period. She suspects that falling violent crime in the Midwest may be largely the result of successful violence reduction in Chicago, and decides to investigate further. Perhaps there were policies implemented in Chicago that could also be successful elsewhere for reducing violent crime.  


## Description of App and Sketch

Our app's landing page will have two panels. The first panel will have a time series plot that can be used to look at trends in crime rates for up to six cities. Users will be able to select the cities using a dropdown menu, and type of crime (assault, homicide, rape, robbery, or total violent crime) using radio buttons, and the range of dates using a slider.

The second panel will be a bar plot for comparing the proportions of total violent crime the specified type of crime comprised in one year for different cities. The cities represented here will be the same as the cities selected for the first panel. Users will be able to select which year they want to view from a dropdown menu. The choice of year will be limited to the range specified for panel one. If total violent crime is selected instead, then the bar plot will show the composition of violent crime. 



